import { createHash } from "node:crypto";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const INPUTS_DIR = fileURLToPath(
  new URL("../samples/inputs/", import.meta.url),
);
const TARGET = fileURLToPath(
  new URL("../packages/engine/src/samples/inputs.ts", import.meta.url),
);

const checkOnly = process.argv.includes("--check");

async function main(): Promise<void> {
  const names = [
    ...new Bun.Glob("*.json").scanSync({ cwd: INPUTS_DIR }),
  ].sort();
  if (names.length === 0) {
    throw new Error("samples/inputs/ contains no JSON packages");
  }

  const texts: { name: string; text: string; digest: string }[] = [];
  for (const name of names) {
    const text = await Bun.file(join(INPUTS_DIR, name)).text();
    // Re-parse so a malformed package fails here rather than in the browser.
    JSON.parse(text);
    texts.push({
      name,
      text,
      digest: createHash("sha256").update(text).digest("hex"),
    });
  }

  const lines: string[] = [
    "/**",
    " * Generated by `bun run scripts/vendor-inputs.ts` — do not edit by hand.",
    " *",
    " * Byte-exact text of every package in `samples/inputs/`, with its SHA-256",
    " * digest, so the browser app, the CLI and the tests import identical bytes",
    " * with no filesystem and no network access.",
    " */",
    "",
    "/** SHA-256 of each vendored package file. */",
    "export const SAMPLE_INPUT_DIGESTS: Record<string, string> = {",
  ];
  for (const entry of texts) {
    lines.push(
      `  ${JSON.stringify(entry.name)}: ${JSON.stringify(entry.digest)},`,
    );
  }
  lines.push(
    "};",
    "",
    "/** Exact file text, keyed by file name. */",
    "export const SAMPLE_INPUTS: Record<string, string> = {",
  );
  for (const entry of texts) {
    lines.push(
      `  ${JSON.stringify(entry.name)}: ${JSON.stringify(entry.text)},`,
    );
  }
  lines.push("};", "");
  const next = lines.join("\n");

  const targetFile = Bun.file(TARGET);
  const previous = (await targetFile.exists()) ? await targetFile.text() : null;
  if (previous === next) {
    console.log(`vendor-inputs: up to date (${texts.length} packages)`);
    return;
  }
  if (checkOnly) {
    console.error(
      "vendor-inputs: packages/engine/src/samples/inputs.ts is stale. Run: bun run vendor-inputs",
    );
    process.exitCode = 1;
    return;
  }
  await Bun.write(TARGET, next);
  console.log(
    `vendor-inputs: wrote ${texts.length} packages to packages/engine/src/samples/inputs.ts`,
  );
}

await main();
